### ISSUE TITLE
UDPInterface_beginConnection fails for either IPv4 or IPv6 peers

### ISSUE THREAD

**Issue by meshpoint** [hyperboria/cjdns#1]
File interface/UDPInterface_admin.c function beginConnection
```c
} else if (Sockaddr_getFamily(&ss.addr) != Sockaddr_getFamily(ctx->udpIf->addr)) {
```
It cheks address family against last added UDPInterface and not the interface specified by interfaceNumber argument. When adding an IPv6 peer to an IPv6 interface it fails with "different address type than this socket is bound to." if the last added interface was IPv4, and vice versa.

**Comment by wfleurant** [comment]
Is this repeatable when adding IPv6 peer through the cjdns API? Only after ./cjdroute < cjdroute.conf had its last UDPInterface added as type IPv4?

**Comment by meshpoint** [comment]
### IPv4 FAIL
#### Config:
```json
"UDPInterface" : [
  {
    "bind" : "0.0.0.0:22038"
  },
  {
    "bind" : "[::]:22038"
  }
]
```
#### Admin:
UDPInterface_beginConnection(address="192.0.2.1:33104") = "different address type than this socket is bound to."
UDPInterface_beginConnection(address="[2001:db8::2]:51071") = success
### IPv6 FAIL
#### Config:
```json
"UDPInterface" : [
  {
    "bind" : "[::]:64575",
  },
  {
    "bind" : "0.0.0.0:64575",
  }
]
```
#### Admin:
UDPInterface_beginConnection(address="192.0.2.3:25882") = success
UDPInterface_beginConnection(address="[2001:db8::4]:47805") = "different address type than this socket is bound to."

**Comment by lgierth** [comment]
Did you try providing an interfaceNumber? I'm not sure whether they start at 0 or 1. The synopsis is:

```
$ /opt/cjdns/tools/cexec 'functions()' | grep UDPInterface
  "UDPInterface_beginConnection(required String publicKey, required String address, String password, Int interfaceNumber)",
  "UDPInterface_new(String bindAddress)",
```

Please reopen if you think there is still an issue.

**Comment by meshpoint** [comment]
Of course it is still an issue. The same code, the same bug, lol. interfaceNumber does not even get to be used in the code before the bug is triggered (not counting checks for presence and sign).
