### ISSUE TITLE
If ipv6 is disabled in a kernel level, cjdroute fails with a cryptic error

### ISSUE THREAD

**Issue by vrde** [hyperboria/cjdns#127]
I tried to run `./cjdroute --genconf > cjdroute.conf` and I got this error:
`1462384502 WARN Configurator.c:111 Got error [Failed to configure tunnel [NetPlatform_linux.c:151 ioctl(SIOCSIFADDR) [Permission denied]]] calling [Core_initTunnel], ignoring.`
## How to reproduce

disable ipv6. My `/etc/sysctl.conf` had:

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.wlan0.disable_ipv6 = 1
```

PS: @Kubuxu that one is for you :smile:

**Comment by kpcyrd** [comment]
Please reopen if this still happens on crashey. :)

**Comment by johnnagro** [comment]
v19.1 happens to me:

`1491749591 WARN Configurator.c:111 Got error [Failed to configure tunnel [NetPlatform_linux.c:153 ioctl(SIOCSIFADDR) [Permission denied]]] calling [Core_initTunnel], ignoring.`

i had to `sysctl net.ipv6.conf.all.disable_ipv6=0` to get it working. not sure why ipv6 was disabled in the first place.
