### ISSUE TITLE
Failed to make function call on any configuration (Mac)

### ISSUE THREAD

**Issue by skadesh** [hyperboria/cjdns#129]
`1463924938 INFO Configurator.c:374 Setting up all ETHInterfaces...
1463924938 INFO Configurator.c:390 Creating new ETHInterface [en0]
1463924943 CRITICAL Configurator.c:97 Failed to make function call [Timed out waiting for a response], error: [ETHInterface_new]
1463924943 CRITICAL Configurator.c:57 enable Log_LEVEL=KEYS to see message content.
1463924948 CRITICAL Configurator.c:69 Failed to stop the core.
1463924948 CRITICAL Configurator.c:71 Aborting.
`
I tried with my configuration from following the instructions, and with a blank config. How could I fix it?

**Comment by ghost** [comment]
It looks like the core process crashed right away -- please post the complete logs

**Comment by skadesh** [comment]
I forgot to run as root, sorry
