### ISSUE TITLE
Deprecate this repository

### ISSUE THREAD

**Issue by kpcyrd** [hyperboria/cjdns#144]
Given issues like #143 and #142 I suggest we deprecate this repository and send everybody back to cjdelisle/cjdns. The few things this repo has actually worked on should be split into different repos on the hyperboria (or fc00) org, like hyperboria/issues and hyperboria/docs.

// @ansuz @cjdelisle @lgierth @hyperboria/core

**Comment by dansup** [comment]
I agree.

**Comment by kpcyrd** [comment]
> I think it's reasonable to say that this PR is entirely too large to review. - ansuz

I'm tempted to just go ahead and rename this repo to `hyperboria/bugs` and push an empty branch and set it as default. Any objections?

**Comment by kpcyrd** [comment]
done
