### ISSUE TITLE
Can cjdns IP be used for user identification?

### ISSUE THREAD

**Issue by sssemil** [hyperboria/cjdns#152]
I'm planning to write a messaging app that runs on cjdns network and right now I'm developing the architecture. Can I use cjdns's IP to identify users? Is it a good idea? Thanks.

**Comment by ansuz** [comment]
some people set up cjdns nodes as gateways to hyperboria for clients that don't run cjdns.

These users would be automatically authenticated as the same user.

It's up to you to decide if that's a bug or a feature.
