### ISSUE TITLE
Janitor / Pinger memory leak

### ISSUE THREAD

**Issue by lgierth** [hyperboria/cjdns#16]
How to find memory leaks: https://github.com/hyperboria/cjdns/blob/master/doc/debugging_memory_leaks.md
Full allocator snapshot: https://ezcrypt.it/1PAn#vsqJLdtrJWPqOLZHwHbPXFVK

```
  | Pinger.c:106 [1296] bytes
  | | RouterModule.c:412 [5176] bytes
  | | | UDPAddrIface.c:100 [64] bytes at [0x7fad97dac7e0]
  | | | UDPAddrIface.c:100 [64] bytes at [0x7fad97dac740]
  | | | Message.h:86 [88] bytes at [0x7fad97af1a30]
  | | | Message.h:75 [2104] bytes at [0x7fad97d69d50]
  | | | Dict.c:132 [72] bytes at [0x7fad97af19e0]
  | | | Dict.c:150 [64] bytes at [0x7fad97af1990]
  | | | Dict.c:132 [72] bytes at [0x7fad97af1940]
  | | | Dict.c:166 [64] bytes at [0x7fad97ae9d50]
  | | | Dict.c:132 [72] bytes at [0x7fad97ae9d00]
  | | | Dict.c:150 [64] bytes at [0x7fad97ae9f90]
  | | | RouterModule.c:414 [104] bytes at [0x7fad97ae9c90]
  | | | Message.h:63 [88] bytes at [0x7fad97ae9c30]
  | | | Message.h:62 [2096] bytes at [0x7fad97d58170]
  | | | RouterModule.c:412 [160] bytes at [0x7fad97ae9ee0]
  | | Timeout.c:84 [488] bytes
  | | | Allocator.c:709 [104] bytes at [0x7fad97df8c70]
  | | | Timeout.c:85 [224] bytes at [0x7fad97df8b80]
  | | | Timeout.c:84 [160] bytes at [0x7fad979397e0]
  | | Timeout.c:84 [488] bytes
  | |   Allocator.c:709 [104] bytes at [0x7fad97d24630]
  | |   Timeout.c:85 [224] bytes at [0x7fad97de1cb0]
  | |   Timeout.c:84 [160] bytes at [0x7fad97989ec0]
  | | Dict.c:132 [72] bytes at [0x7fad97ae9e90]
  | | Dict.c:166 [64] bytes at [0x7fad97ae9e40]
  | | Dict.c:132 [72] bytes at [0x7fad97989f70]
  | | Dict.c:166 [64] bytes at [0x7fad97908630]
  | | String.c:39 [64] bytes at [0x7fad979085e0]
  | | String.c:31 [64] bytes at [0x7fad97de1da0]
  | | Dict.c:132 [72] bytes at [0x7fad97d0aca0]
  | | Dict.c:166 [64] bytes at [0x7fad97d0ac50]
  | | Dict.c:95 [56] bytes at [0x7fad97d0d500]
  | | RouterModule.c:581 [176] bytes at [0x7fad97d0ab90]
  | | Allocator.c:709 [104] bytes at [0x7fad97b092c0]
  | | String.c:39 [64] bytes at [0x7fad97dfa5e0]
  | | String.c:31 [64] bytes at [0x7fad97dfa590]
  | | Pinger.c:116 [136] bytes at [0x7fad97d108b0]
  | | Pinger.c:106 [160] bytes at [0x7fad97d10800]
```

**Comment by areyoueye** [comment]
Following the instructions at https://github.com/hyperboria/cjdns/blob/master/doc/debugging_memory_leaks.md we have:

$ cat cjdnsmemdump | sed -n -e 's/.* \([a-zA-Z0-9_]*\.[ch]\:[0-9]*\) .*$/\1/p' | sort | uniq -c | sort -n
      1 Admin.c:481
      1 Admin.c:518
      1 AdminLog.c:350
      1 Allocator_admin.c:60
      1 AuthorizedPasswords.c:111
      1 AverageRoller.c:28
      1 cjdroute2.c:563
      1 cjdroute2.c:567
      1 cjdroute2.c:612
      1 cjdroute2.c:653
      1 Configurator.c:323
      1 Configurator.c:369
      1 Configurator.c:518
      1 Configurator.c:524
      1 Configurator.c:529
      1 Configurator.c:541
      1 Configurator.c:546
      1 Configurator.c:630
      1 ControlHandler.c:203
      1 ConverterV15.c:222
      1 Core.c:207
      1 Core.c:234
      1 Core.c:251
      1 Core.c:254
      1 CryptoAuth.c:937
      1 CryptoAuth.c:940
      1 DevUrandomRandomSeed.c:66
      1 DHTModuleRegistry.c:28
      1 DHTModuleRegistry.c:30
      1 EncodingSchemeModule.c:142
      1 ETHInterface_admin.c:185
      1 EventBase.c:65
      1 EventEmitter.c:332
      1 EventEmitter.c:348
      1 FileWriter.c:46
      1 IndirectLog.c:48
      1 InterfaceController_admin.c:179
      1 InterfaceController.c:953
      1 IpTunnel_admin.c:211
      1 IpTunnel.c:72
      1 IpTunnel.c:731
      1 Janitor.c:683
      1 LibuvEntropyProvider.c:58
      1 LibuvEntropyProvider.c:59
      1 LinuxRandomUuidSysctlRandomSeed.c:50
      1 NetCore.c:40
      1 NetCore.c:49
      1 NodeStore_admin.c:275
      1 NodeStore.c:1760
      1 NodeStore.c:1764
      1 Pathfinder.c:436
      1 Pipe.c:134
      1 Pipe.c:253
      1 Pipe.c:344
      1 Pipe.c:358
      1 ProcSysKernelRandomUuidRandomSeed.c:98
      1 Random.c:232
      1 Random.c:238
      1 RandomSeed.c:42
      1 RandomSeed.c:64
      1 RandomSeed.c:82
      1 RandomSeed.c:93
      1 ReplyModule.c:51
      1 Router.c:74
      1 RouterModule_admin.c:340
      1 RouterModule.c:211
      1 RouterModule.c:218
      1 SearchRunner_admin.c:152
      1 SearchRunner.c:398
      1 SearchStore.c:54
      1 Security_admin.c:153
      1 Security.c:152
      1 SerializationModule.c:47
      1 SessionManager_admin.c:126
      1 SessionManager.c:547
      1 Sockaddr.c:288
      1 SwitchAdapter.c:74
      1 SwitchCore.c:302
      1 SwitchPinger_admin.c:115
      1 SwitchPinger.c:340
      1 SwitchPinger.c:355
      1 SystemRandomSeed.c:36
      1 TUNAdapter.c:159
      1 UDPAddrIface.c:255
      1 UDPInterface_admin.c:179
      1 UpperDistributor.c:83
      1 WriterLog.c:76
      2 AdminClient.c:333
      2 Configurator.c:346
      2 Configurator.c:385
      2 ETHInterface_linux.c:233
      2 EventBase.c:64
      2 Event.c:70
      2 EventEmitter.c:331
      2 InterfaceController.c:813
      2 Janitor.c:671
      2 NodeStore.c:1749
      2 Penalty.c:108
      2 Pinger.c:184
      2 Pipe.c:231
      2 Pipe.c:334
      2 RouterModule_admin.c:334
      2 SearchRunner.c:390
      2 SessionManager.c:110
      2 UDPAddrIface.c:249
      2 UDPInterface_admin.c:122
      3 InterfaceController.c:695
      3 RandomSeed.c:50
      3 UDPAddrIface.c:294
      4 ETHInterface_admin.c:86
      4 Event.c:65
      4 InterfaceController.c:809
      4 Map.h:181
      4 Map.h:184
      4 Map.h:190
      4 RumorMill.c:139
      4 RumorMill.c:140
      4 RumorMill.c:142
      4 Sockaddr.c:195
      4 Sockaddr.c:72
      6 ArrayList.c:34
      6 ArrayList.c:35
      6 Map.h:195
      8 RumorMill.c:136
     19 NodeStore.c:1975
     19 NodeStore.c:1976
     19 SearchRunner.c:360
     19 SearchStore.c:69
     38 SearchRunner.c:328
     66 Dict.c:199
     86 NodeStore.c:1481
     89 EncodingScheme.c:377
     89 EncodingScheme.c:383
     89 SessionManager.c:191
     91 CryptoAuth.c:1064
    172 NodeStore.c:1480
    178 SessionManager.c:190
    205 NodeStore.c:113
    380 NodeStore.c:2015
    964 RouterModule.c:414
    964 RouterModule.c:581
    965 Pinger.c:116
    967 Message.h:62
    967 Message.h:63
    970 Message.h:75
    970 Message.h:86
   1081 Dict.c:95
   1818 String.c:31
   1818 String.c:39
   1916 UDPAddrIface.c:100
   1928 RouterModule.c:412
   1930 Pinger.c:106
   1994 Dict.c:150
   2001 Timeout.c:85
   3003 Allocator.c:709
   3801 Dict.c:166
   4002 Timeout.c:84
   5861 Dict.c:132

**Comment by lgierth** [comment]
Haven't seen this one again.
