### ISSUE TITLE
Enable Tip4Commit for crashey branch

### ISSUE THREAD

**Issue by 8341696379** [hyperboria/cjdns#163]
Hi there,

could Tip4Commit be enabled for the crashey branch? It seems like it's the main development branch of the project. Due to the Bitcoin price volatility it'd be nice if the tips could be handed out in some viable timeframe, which is currently not happening due to crashey being merged over to master every few months.

Thanks

**Comment by cjdelisle** [comment]
Hello '79,

I managed to login to t4c and I was able to change the branch to crashey. Let me know if that helps.

Caleb

**Comment by 8341696379** [comment]
Thanks for reaching out.

It looks like changing the branch to `crashey` will discard the tips for the commits that haven't yet been merged to `master` (a total of 75 commits).

This is because Tip4Commit compares the pushed changes with the current branch "state" and iterates over the new commits.

My suggestion is to revert T4C back to master, merge crashey to master (in order to process the mentioned 75 commits) and then change T4C to crashey.

Have a nice day!

@cjdelisle

**Comment by cjdelisle** [comment]
I don't want to merge to master at this moment but I can make a temp branch to allow this

**Comment by cjdelisle** [comment]
oh you're not gonna believe this... tip4commit is apparently down due to some certificate stuff, anyway I todolisted this

**Comment by 8341696379** [comment]
alright, thanks so much :)

**Comment by 8341696379** [comment]
ok - looks like it's up though YMMV

**Comment by cjdelisle** [comment]
Check if it worked, it should be fixed and on crashey

**Comment by 8341696379** [comment]
Looks fine! Thanks :)
