### ISSUE TITLE
 Different sha512sums value in version 20

### ISSUE THREAD

**Issue by rgdoliveira** [hyperboria/cjdns#167]
Alpine Linux builds cjdns and it downloads the 20 version source from [github](https://github.com/cjdelisle/cjdns/archive/cjdns-v20.tar.gz)

We are rebuilding all the Alpine packages for 3.7 release but cjdns failed to build when comparing the sha512sums. It was before:
sha512sums="7da6537ed417d33ebd9ffa27a9e08758c48ea99930a85497853f0ee43cc87501434ab76bee0e69dc935b3338959d86bcb4bef527f1b93887b0a3662b4ab55879  cjdns-20.tar.gz"

And now:
sha512sums="afa63daea3c3bd3e16dd0a326ebdc2afcb411c595e66552c3156c59c36af21c0b2278b3299b1053b98d381790311beeb14547afdf3d182170c446867d2199a94  cjdns-20.tar.gz"

Does this tar.gz got any changes or it was uploaded again (or something like that)?

**Comment by kpcyrd** [comment]
welcome! I'm interested in reviewing the diff, could you upload the old version (7da6537ed4...) somewhere? I'm not sure if the release was re-tagged. (cc @cjdelisle?)

**Comment by cjdelisle** [comment]
I don't remember ever double-releasing the v20 tag so indeed checking the diff might be prudent. It's probably my fault though and I just can't remember :|

**Comment by rgdoliveira** [comment]
I don't have the tarball of the older version. I just tried to build  cjdns for Alpine 3.7 release and noticed that sha512sums didn't match. But it can be something related with github (I guess) as you said that the released tarball wasn't changed.

**Comment by rgdoliveira** [comment]
I'm going to close it. It seems a Github "issue" as it also happened with other projects.
