### ISSUE TITLE
About (the lack of) forward secrecy.

### ISSUE THREAD

**Issue by ccaapton** [hyperboria/cjdns#177]
In many parts of the documentation, namely sessionStats.md, Readme, and faq/security.md, they claim CJDNS has Perfect Forward Secrecy. Only the whitepaper acknowledged the lack of PFS.

PFS is usually provided by Diffie-Hellman key exchange: If a middle adversary records all the traffic between two parties Alice and Bob, and somehow gets hands on Alice's permanent private key, all CJDNS historical communication from Alice to Bob will be compromised, because the adversary can compute Alice's temp keys from the historical packets. But with DH key exchange, permanent key and history traffic are not enough to derive past temporary keys, because temp keys are never sent over the wire.

The current documentation states "Temporary keys are used and destroyed when cryptAuth sessions time out", but you can never destroy anything you sent over the wire! The "PFS" in CJDNS's documents is not what PFS commonly perceived in the crypto field.

So when will you add something like ECDH?

**Comment by progval** [comment]
cjdns does have PFS. When doing the handshake, each peer generates a temporary key pair, and sends the public key to the other peer; and these temporary keys are used to (derive a symmetric secret used to) encrypt the traffic after the handshake.

**Comment by ccaapton** [comment]
Got it, thx! Will close.
