### ISSUE TITLE
triggering assertion failures via admin port

### ISSUE THREAD

**Issue by ansuz** [hyperboria/cjdns#23]
I started playing around with the admin interface, which I haven't done in a while, and I found I could trigger crashes by calling certain functions.

```
[ansuz@blackbox tools]$ ./cexec "RouterModule_getPeers('0000.0000.0000.0001',10000,'0000.0000.0000.0001')"
/home/ansuz/code/cjdns/tools/cexec:35
        if (err) { throw err; }
                         ^
Error: timeout after 10000ms
    at null._onTimeout (/home/ansuz/code/cjdns/contrib/nodejs/cjdnsadmin/cjdnsadmin.js:27:18)
    at Timer.listOnTimeout (timers.js:110:15)
```

In addition to the timeout error, I get this assertion failure.

`Assertion failure [RouterModule.c:557] [(addr->path != 1)]`

I'm going to keep on looking into this, and try out the other functions in RouterModule, but maybe other people can look into it as well.

**Comment by ansuz** [comment]
Follow-up: I'm not _quite_ running the latest crashey, but it's fairly recent. The line in question is [not in master](https://github.com/cjdelisle/cjdns/blob/master/dht/dhtcore/RouterModule.c#L555-L556), but [can still be found in the latest crashey](https://github.com/cjdelisle/cjdns/blob/crashey/dht/dhtcore/RouterModule.c#L544-L546).

I'm not sure why we shouldn't be pinging ourselves, but it seems like a fairly minor thing to crash over. This might be for debugging purposes, making cjdns fragile enough that we notice when it does something odd, but it seems like this kind of thing should be handled more gracefully.

I stumbled across it while starting to trying to recurse across the network graph. In any case, if this is going to stay, it should be well documented.

**Comment by cjdelisle** [comment]
ok to drop it, at one point it caused a crypto fuckup but ping-self was reworked to be handled as a special case as I recall

**Comment by ansuz** [comment]
played it safe and commented it out, PR sent.
