### ISSUE TITLE
build fails on 64-bit MIPS targets

### ISSUE THREAD

**Issue by dangowrt** [hyperboria/cjdns#27]
See e.g. http://buildbot.openwrt.org:8010/broken_packages/octeon/cjdns/compile.txt
The Ubiquiti Edge Router Lite based on the octeon SoC is a very promissing target for cjdns imho...

**Comment by dangowrt** [comment]
Also affects netlogic target
http://buildbot.openwrt.org:8010/broken_packages/netlogic/cjdns/compile.txt

**Comment by lgierth** [comment]
Probably fixed on hyperboria:master, added a mips64 plan.
