### ISSUE TITLE
ETHInterface on OS X

### ISSUE THREAD

**Issue by lgierth** [hyperboria/cjdns#31]
@ksnieck wrote some code for this here: https://github.com/ksnieck/cjdns/tree/osxeth

It probably needs a refresh, and I remember them saying it crashed under load.

**Comment by ksnieck** [comment]
I never figured out how to use the memory management thing, but yea, Berkeley Packet Filter, appears to be the only way to see ethernet frames on mac os.

**Comment by wfleurant** [comment]
Testing going well (over 20min so far, no hiccups) 71f05cb1bb3aefcdea86c35b2491feb8583fef0a 

calling os x testers @ksnieck @lukevers

**Comment by interfect** [comment]
I've been using the Mac ETHInterface for weeks. It seems to work fine, but needs a cjdns restart when WiFi connects in order to actually work. I don't think that's an OS X specific problem, though.

**Comment by wfleurant** [comment]
if you have set up your daemon to start cjdns.. you could throw and exception when the ETHInterface goes down.. and hopefully this race condition between the restart of the interface and the cjdroute process fixes it.. hmm https://github.com/wfleurant/cjdns/commit/094c011c48598c3cfa28493ce90a91c21688fc07

**Comment by lgierth** [comment]
ETHInterface_darwin is a thing now
