### ISSUE TITLE
Assertion failure [NodeStore.c:423] [(r < Node_getReach(link->parent))]

### ISSUE THREAD

**Issue by dangowrt** [hyperboria/cjdns#34]
still on current hyperboria/cjdns?branch=master as well as cjdelisle/cjdns?branch=crashey

After a while (24h+):
Assertion failure [NodeStore.c:423] [(r < Node_getReach(link->parent))]

**Comment by lgierth** [comment]
Seen this too yesterday

**Comment by lgierth** [comment]
Hopefully fixed by a05ade40dc31caebaf3aa770aac3ab2ecb02d867
