### ISSUE TITLE
Could not find user...

### ISSUE THREAD

**Issue by sssemil** [hyperboria/cjdns#72]
Any ideas why it's happening?

    1446479476 INFO Configurator.c:135 Checking authorized password 0.
    1446479476 INFO Configurator.c:159 Adding authorized password #[0] for user [default-login].
    1446479476 INFO Configurator.c:374 Setting up all ETHInterfaces...
    1446479476 CRITICAL Configurator.c:107 Got error [Could not find user [No such file or directory]] calling [Security_getUser]
    1446479476 CRITICAL Configurator.c:57 enable Log_LEVEL=KEYS to see message content.
    1446479476 CRITICAL Configurator.c:71 Aborting.

Thanks.

**Comment by Kubuxu** [comment]
What user do you have set under security in your `cjdroute.conf` and does this user exists?

**Comment by kpcyrd** [comment]
I'm guessing `/etc/passwd` is missing.

**Comment by sssemil** [comment]
Oh, thanks. Changed user, now works(mostly cus i'm on android)
