### ISSUE TITLE
Fails to link __cmsg_nxthdr on Android 4.4.4

### ISSUE THREAD

**Issue by benhylau** [hyperboria/cjdns#93]
Just did a build on https://github.com/hyperboria/cjdns/commit/914519757271a1d4ef2c5d848508497b30fa4005 and ran **cjdroute** on a rooted Nexus S with Android 4.4.4.

I get this error:

```
127|root@crespo:/data/data/berlin.meshnet.cjdns # ./cjdroute                                                     │I/CjdnsService( 3664): onDestroy
CANNOT LINK EXECUTABLE: cannot locate symbol "__cmsg_nxthdr" referenced by "./cjdroute"...
```

Same issue as https://github.com/hyperboria/cjdns/pull/61#issuecomment-168099044

Note that this phone has successfully run **cjdroute** binaries built from a previous version of the code.

**Comment by sssemil** [comment]
Looks like you built it with android-21. Not sure but try finding all files conaning that and replace it woth android-9 or 16.
