### ISSUE TITLE
NodeJS Admin Page doesn't launch

### ISSUE THREAD

**Issue by IlyaBizyaev** [hyperboria/cjdns#98]
Here is the output:
```
undefined:112
        "ETHInterface":
        ^^^^^^^^^^^^^^
SyntaxError: Unexpected string
    at CJDNS.parseConfig (/home/ilya/cjdns/contrib/nodejs/admin/cjdns.js:41:22)
    at new CJDNS (/home/ilya/cjdns/contrib/nodejs/admin/cjdns.js:21:10)
    at Object.<anonymous> (/home/ilya/cjdns/contrib/nodejs/admin/admin.js:30:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by chpio** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Wa: try adding the ethinterface Option into the cjdns config

Am 20. Januar 2016 11:24:37 MEZ, schrieb Ilya Bizyaev <notifications@github.com>:
>Here is the output:
>```
>undefined:112
>        "ETHInterface":
>        ^^^^^^^^^^^^^^
>SyntaxError: Unexpected string
>at CJDNSparseConfig
>(/home/ilya/cjdns/contrib/nodejs/admin/cjdnsjs:41:22)
>    at new CJDNS (/home/ilya/cjdns/contrib/nodejs/admin/cjdnsjs:21:10)
>at Object<anonymous>
>(/home/ilya/cjdns/contrib/nodejs/admin/adminjs:30:13)
>    at Module_compile (modulejs:456:26)
>    at ObjectModule_extensionsjs (modulejs:474:10)
>    at Moduleload (modulejs:356:32)
>    at FunctionModule_load (modulejs:312:12)
>    at FunctionModulerunMain (modulejs:497:10)
>    at startup (nodejs:119:16)
>    at nodejs:902:3
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hyperboria/cjdns/issues/98

- --
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
-----BEGIN PGP SIGNATURE-----

iQI2BAEBCgAgGRxUaG9tYXMgSGVjayA8dEBiMTI4Lm5ldD4FAlafZMQACgkQAhDw
lcr2vhnUng//f8YPBTr6wqWk6R3HNxIZfQ6UGMxr1Hw46Shxw/vF025yfEUuYD19
galSj0mYV0f7DeOQowLujArfoZQL+PxY812lhtp/nYZSJj/mZwudShuzIivqAbnq
bNNeBhwLW2wGd5mf2AfEAXsbNPkxYqYpx6ukEACX8Thp3QSDoXX77uYJ2/+sZh5h
nVQnt71vU3Q9c8aq+FkIjQ/n+8NQ3QEjRV3BDGPcZeSUi2uOgw+qJXxuPAeSnF5P
FpCF78orB75LVVFkNq1ZjuL0oB7O9/MSNUovTyaXeQS+hTpnWOtQ7lzq3FDc6GZi
3MRUr8OnHTPC+nDnPwcvglIHTJOR4UFEX2czY8mQu3tB5Jn+hTQ4jU11r1TMsE4B
h5XYf1vzMCMJDLHqyxw1/ZCJQpFYDV8TpF8hnNG90QQwoo42uQt4G+dSDoedCimH
hapfbgoyrnSaNgudJnjC5GQHcNrgVFnFwjWIW/4KLqCX+H4aAAUBC5QTRTA1ur0f
P86oImu43tKQpPC8iZdqkJ98kO/+TqBvzYsHFDGXYHqOHra/2WNhVsxYTd+xn9BO
jXrrYgNS1ao8PEqYTiGIBDBk50rSfhC0FZTVQiMdqkwq36yzISjfCUGqRSlLd5DO
13JlFT3pXMm+DyRLxoSz4thj8yGbwh/HNJScBsr631KIxAXeLv5YA7k=
=+/JT
-----END PGP SIGNATURE-----

**Comment by IlyaBizyaev** [comment]
I'm afraid i don't quite understand you. Here is the diff between the auto-generated `cjdroute.conf` and my current configuration:
```
91,96d90
<                     // Moscow public node
<                     "83.137.52.57:31337":
<                     {
<                            "password": "cjdnsDotixDotgs",
<                            "publicKey": "pvtgk72f25urxqywxdzfk12t2b4kuhtrc2f1mx58rtpx0wzbll90.k"
<                     }
```
By the way, when I launch `cjdroute`, it says that connection is successful, but Hyperboria websites (e.g. socialno.de) do not launch.

**Comment by lgierth** [comment]
There's simply a comma missing before `"ETHInterface"`

**Comment by IlyaBizyaev** [comment]
OK, it now works. Thanks.
